import "./ImplementationPlan.css";

export default function ImplementationPlan({ setCurrentStep }) {
    return (
        <div className="implementation-page">

            <div className="implementation-card">

                <div className="implementation-header">
                    <h1>Pipeline Implementation Plan</h1>
                    <p>
                        Final deployment setup instructions for your DevOps pipeline.
                    </p>
                </div>

                {/* SECRETS */}
                <div className="plan-section">
                    <h2>Environment Secrets</h2>

                    <div className="secret-grid">
                        <div className="secret-card">
                            <span>AWS_ACCESS_KEY_ID</span>
                            <p>AWS deployment authentication key</p>
                        </div>
                        <div className="secret-card">
                            <span>AWS_SECRET_ACCESS_KEY</span>
                            <p>AWS secret key</p>
                        </div>
                        <div className="secret-card">
                            <span>GHCR_TOKEN</span>
                            <p>GitHub container registry token</p>
                        </div>
                        <div className="secret-card">
                            <span>KUBE_CONFIG</span>
                            <p>Kubernetes cluster configuration</p>
                        </div>
                    </div>
                </div>

                {/* STEPS */}
                <div className="plan-section">
                    <h2>Implementation Steps</h2>

                    <div className="step-card">
                        <span>1</span>
                        <div>
                            <h3>Add GitHub Secrets</h3>
                            <p>Add all environment variables inside repository settings.</p>
                        </div>
                    </div>

                    <div className="step-card">
                        <span>2</span>
                        <div>
                            <h3>Configure Container Registry</h3>
                            <p>Connect GitHub Container Registry or Docker Hub.</p>
                        </div>
                    </div>

                    <div className="step-card">
                        <span>3</span>
                        <div>
                            <h3>Deploy Kubernetes Cluster</h3>
                            <p>Configure kubectl and deployment manifests.</p>
                        </div>
                    </div>

                    <div className="step-card">
                        <span>4</span>
                        <div>
                            <h3>Push Repository</h3>
                            <p>Push code to trigger the CI/CD pipeline automatically.</p>
                        </div>
                    </div>

                    <div className="implementation-actions">

                        {/* DEPLOY TO GITHUB  ← NEW */}
                        <button
                            className="impl-btn primary"
                            onClick={() => setCurrentStep(7)}
                        >
                            🚀 Deploy to GitHub
                        </button>

                        {/* DOWNLOAD PLAN */}
                        <button
                            className="impl-btn secondary"
                            onClick={() => {
                                const content = `
PIPELINE IMPLEMENTATION PLAN

1. Add GitHub Secrets
2. Configure Registry
3. Deploy Kubernetes
4. Push Repository

Generated by PipeGen AI Pipeline Generator
                                `;
                                const blob = new Blob([content], { type: "text/plain" });
                                const url = URL.createObjectURL(blob);
                                const a = document.createElement("a");
                                a.href = url;
                                a.download = "implementation-plan.txt";
                                a.click();
                                URL.revokeObjectURL(url);
                            }}
                        >
                            ⬇ Download Full Plan
                        </button>

                        {/* EXPORT ZIP */}
                        <button
                            className="impl-btn secondary"
                            onClick={() => alert("ZIP Export Feature Coming Soon 🚀")}
                        >
                            📦 Export ZIP
                        </button>

                        {/* START OVER */}
                        <button
                            className="impl-btn danger"
                            onClick={() => window.location.reload()}
                        >
                            ↺ Start Over
                        </button>

                    </div>
                </div>

            </div>
        </div>
    );
}