name: Smart CI/CD Pipeline

on:
  push:
    branches: [main, develop, release/*]
  workflow_dispatch:

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache Node Modules
        uses: actions/cache@v3

        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Application
        run: npm run build

      - name: SAST Scan
        run: echo "Running SAST Scan..."

      - name: Dependency Vulnerability Scan
        run: npm audit --audit-level=high

      - name: Build Docker Image
        run: docker build -t myapp:latest .

  publish:

    needs: build-and-test

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Push Image to GitHub Container Registry
        run: echo "Pushing Docker image to GitHub Container Registry..."


  deploy-development:

    needs: publish

    runs-on: ubuntu-latest

    environment: Development

    steps:

      - name: Deploy to AWS ECS / EC2

        run: echo "Deploying to AWS ECS..."
